import React, { useState, useEffect } from 'react';
import { Bell, CheckCircle2, ShieldAlert, ArrowRight, Check } from 'lucide-react';
import api from '../services/api';
import StatusBadge from '../components/StatusBadge';
import LoadingSkeleton from '../components/LoadingSkeleton';
import { useNavigate } from 'react-router-dom';
import { useSocket } from '../context/SocketContext';

const Alerts = () => {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const { setUnreadAlertsCount } = useSocket();
  const navigate = useNavigate();

  const fetchAlerts = async () => {
    try {
      const res = await api.get('/alerts');
      setAlerts(res.data);
      const unread = res.data.filter(a => !a.read).length;
      setUnreadAlertsCount(unread);
    } catch (err) {
      console.error('Error fetching alerts:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAlerts();
  }, []);

  const handleMarkRead = async (alertId) => {
    try {
      await api.patch(`/alerts/${alertId}`, { read: true });
      setAlerts(prev => prev.map(a => a._id === alertId ? { ...a, read: true } : a));
      setUnreadAlertsCount(prev => Math.max(0, prev - 1));
    } catch (err) {
      console.error('Error marking alert read:', err);
    }
  };

  const handleMarkResolved = async (alertId) => {
    try {
      await api.patch(`/alerts/${alertId}`, { status: 'Resolved', read: true });
      setAlerts(prev => prev.map(a => a._id === alertId ? { ...a, status: 'Resolved', read: true } : a));
    } catch (err) {
      console.error('Error resolving alert:', err);
    }
  };

  return (
    <div className="space-y-6">
      <div className="glass-card rounded-xl p-5 border border-slate-200/80 shadow-xs flex items-center justify-between">
        <div>
          <h2 className="text-lg font-extrabold text-slate-900 tracking-tight flex items-center gap-2">
            <Bell className="w-5 h-5 text-emerald-600" />
            Security Alerts Center
          </h2>
          <p className="text-xs text-slate-500">Active High & Critical security notifications generated by ML rules</p>
        </div>
      </div>

      <div className="glass-card rounded-xl border border-slate-200/80 shadow-xs overflow-hidden">
        {loading ? (
          <div className="p-6">
            <LoadingSkeleton count={4} height="h-16" />
          </div>
        ) : (
          <div className="divide-y divide-slate-100">
            {alerts.length === 0 ? (
              <div className="p-8 text-center text-slate-400 italic">No security alerts available.</div>
            ) : (
              alerts.map((alert) => (
                <div
                  key={alert._id}
                  className={`p-4 flex items-center justify-between transition-colors ${
                    !alert.read ? 'bg-amber-50/30' : 'hover:bg-slate-50'
                  }`}
                >
                  <div className="flex items-center gap-4">
                    <div className={`p-2.5 rounded-xl ${
                      alert.severity === 'Critical' ? 'bg-rose-100 text-rose-700' : 'bg-amber-100 text-amber-700'
                    }`}>
                      <ShieldAlert className="w-5 h-5" />
                    </div>

                    <div>
                      <div className="flex items-center gap-2">
                        <h4 className="text-xs font-extrabold text-slate-900">{alert.message}</h4>
                        <StatusBadge status={alert.severity} />
                        {!alert.read && <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-amber-500 text-white">NEW</span>}
                      </div>
                      <p className="text-[11px] text-slate-500 font-medium mt-0.5">
                        Threat: {alert.threatType} | Risk Score: {alert.riskScore}/100 | {new Date(alert.createdAt).toLocaleString()}
                      </p>
                    </div>
                  </div>

                  <div className="flex items-center gap-2">
                    {!alert.read && (
                      <button
                        onClick={() => handleMarkRead(alert._id)}
                        className="p-1.5 text-slate-400 hover:text-slate-700 rounded-lg hover:bg-slate-200 transition-colors"
                        title="Mark as Read"
                      >
                        <Check className="w-4 h-4" />
                      </button>
                    )}

                    {alert.incidentId && (
                      <button
                        onClick={() => navigate(`/incidents/${alert.incidentId}`)}
                        className="px-3 py-1.5 bg-slate-100 hover:bg-emerald-50 text-slate-700 hover:text-emerald-700 font-bold text-xs rounded-lg border flex items-center gap-1 transition-colors"
                      >
                        Open Incident <ArrowRight className="w-3.5 h-3.5" />
                      </button>
                    )}
                  </div>
                </div>
              ))
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default Alerts;
